pipeline {
  agent {
    node {
      label 'master'
    }

  }
  stages {
    stage('init') {
      steps {
        script {
          gv = load "script.groovy"
        }

      }
    }

    stage('Checkout_app repository') {
      parallel {
        stage('Checkout_app repository') {
          steps {
            echo "Checking out app version ${NEW_VERSION}"
            echo '====++++Try to load groovy script++++===='
            script {
              gv.buildApp()
            }

          }
        }

        stage('') {
          steps {
            sleep 5
          }
        }

      }
    }

    stage('Run_deploy application') {
      parallel {
        stage('Deploying application') {
          steps {
            echo 'Starting deploying app'
            script {
              gv.deployApp()
            }

          }
        }

        stage('Copy files') {
          steps {
            echo 'Copying files of app'
            script {
              gv.copyFilesToProd()
            }

          }
        }

      }
    }

    stage('Emails') {
      steps {
        echo 'Send letters'
      }
    }

  }
  environment {
    NEW_VERSION = '1.20.0'
  }
  post {
    always {
      echo 'I will always run regardless of the completion status of the Pipeline’s or stage’s run.'
    }

    failure {
      echo 'I will when job will failure'
    }

    success {
      echo 'I will run when job is success'
    }

  }
  parameters {
    booleanParam(name: 'RSU present', defaultValue: true, description: 'Is RSU present on bench')
    choice(name: 'Version to build', choices: ['1.20', '1.30', '1.40'], description: 'Pick version')
  }
}