pipeline {
  agent {
    node {
      label 'master'
    }

  }
  stages {
    stage('Stage 1') {
      parallel {
        stage('Checkout Stage RELEASE') {
          steps {
            echo 'Checking out Stage RELESE'
          }
        }

        stage('Checkout Stage 2 RELEASE') {
          steps {
            echo 'Checkout Stage RELEASE'
          }
        }

      }
    }

    stage('Start tests RELEASE') {
      agent any
      steps {
        echo 'Starting testin'
      }
    }

  }
}
