pipeline {
  agent {
    node {
      label 'master'
    }

  }
  stages {
    stage('Stage 1 NTG7-F1KH') {
      parallel {
        stage('Checkout Stage 1 NTG7-F1KH') {
          steps {
            echo 'Checking out Stage 1'
          }
        }

        stage('Checkout Stage 2 NTG7-F1KH') {
          steps {
            echo 'Checkout Stage NTG7-F1KH'
          }
        }

      }
    }

    stage('Start tests STAR2') {
      agent any
      steps {
        echo 'Starting testin'
      }
    }

  }
}
